apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appchart.fullname" . }}-appname
  labels:
  {{- include "appchart.labels" . | nindent 4 }}
data:
  startup_yr: {{ required "appname.startupYr is required" .Values.appname.startupYr
    | b64enc | quote }}