apiVersion: v1
kind: Service
metadata:
  name: {{ include "appchart.fullname" . }}-service
  labels:
  {{- include "appchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: appname
  {{- include "appchart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.service.ports | toYaml | nindent 2 -}}