apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: <your-private-image>
  imagePullSecrets:
  - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appname-deployment
spec:
  selector:
    matchLabels:
      app: appname
  template:
    metadata:
      labels:
        app: appname
    spec:
      containers:
      - name: appname
        image: nimboya/eks-helm-test:latest
      imagePullSecrets:
      - name: regcred
        env:
        - name: STARTUP_YR
          valueFrom:
            secretKeyRef:
              name: appname
              key: startup_yr
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: appname-service
spec:
  type: LoadBalancer
  selector:
    app: appname
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: appname
data:
  startup_yr: MjAyMw==
