name: Setup EKS

on:
  push:
    branches:
      - "eks"

jobs:
  build-deploy-app:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      FULL_IMAGE_NAME: ${{ steps.build-container.outputs.ECR_IMAGE }}
      DOCKER_IMAGE_TAG: ${{ steps.build-container.outputs.DOCKER_IMAGE_TAG }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Workflow
        run: |
          terraform init
          terraform plan
          terraform apply
      